### ISSUE TITLE
More documentation / examples

### ISSUE THREAD

**Issue by rickerd** [ruudk/PaymentMollieBundle#10]
Sorry, my skills in Symfony aren't so great either.
Is there a way to add more examples or documentation?

I'm working on a AngularJS project and i have a RESTFUL API that communicates with my AngularJS application.

But i want to retrieve all the banks (via json) and so on.
I hope you can give me a little help or start to work with.

**Comment by ruudk** [comment]
This bundle heavily relies on http://jmsyst.com/bundles/JMSPaymentCoreBundle. If you want a more easier way to communicate with Mollie, you can also just use their PHP SDK directly.

**Comment by rickerd** [comment]
I know but i want to use the neat bundle.
I see in the services.xml that the banks are present but my skills arent that great yet so i was aiming for some examples or documentation on how to use it.

**Comment by regularjack** [comment]
JMSPaymentCoreBundle's [documentation](http://jmspaymentcorebundle.readthedocs.io/) as recently been significantly improved. Take a look and feel free to open issues on JMSPaymentCore if you think something is missing from the docs.
