### ISSUE TITLE
Support for locale

### ISSUE THREAD

**Issue by Fordiag** [ruudk/PaymentMollieBundle#19]
Is it possible to transmit the locale to mollie? 

I tried to pass 'locale' => 'fr' in predefined data but doesn't seem to work?

Thank you in advance

**Comment by ruudk** [comment]
Does Omnipay Mollie support it?

If so, then it should be added here somewhere : https://github.com/ruudk/PaymentMollieBundle/blob/master/src/Plugin/IdealPlugin.php#L47

**Comment by Fordiag** [comment]
I think yes :  [Here pull request](https://github.com/thephpleague/omnipay-mollie/pull/23)
I have to edit your vendor?

**Comment by ruudk** [comment]
That PR is not merged yet... It first needs to be merged, and tagged, then we can see if this bundle can be updated to use latest version of Omnipay.

**Comment by Fordiag** [comment]
Ok I managed to override the defaultPlugin (getPurchaseParameters), the Gateway, and PurchaseRequest (of Omnipay). I am able to send the locale now.
The logs shows that the locale is correctly sent by POST, but the TEST payment page is always in Dutch.
Do you now if the PROD payment page will correctly be shown with 'locale' parameter?

**Comment by ruudk** [comment]
Good question, I really don't know. You should ask Mollie. They respond fast :)

**Comment by Fordiag** [comment]
They replied to me, it's correct, the Test payment page is always in dutch...
Prod change with the locale parameter.

**Comment by willemstuursma** [comment]
@Fordiag sorry about that, it's on our road map. You should definitely send full ISO locales, e.g. `fr_FR` or `fr_BE`.

**Comment by Fordiag** [comment]
Hello Willem, in the doc, I read "One of: de, en, es, fr, be, be-fr, nl" .
I don't know if underscore will work. Maybe you know better than me ;-)

**Comment by willemstuursma** [comment]
Check out: https://www.mollie.com/en/docs/reference/payments/create. We definitely recommend sending full ISO locales now. 

> Allow you to preset the language to be used in the payment screens shown to the consumer. When this parameter is not provided, the browser language will be used instead (which is usually more accurate). You can use any ISO 15897 locale.

Due to backwards compatibility reasons, you will get a custom two char locale value back from the API though. But you can send the full length and they are preferred. In a future API version we will revise this.

**Comment by Fordiag** [comment]
The doc has certainly been updated which is good.
Thank you for your feedback, I will change my code to send full ISO locales.
