### ISSUE TITLE
Payment method support 

### ISSUE THREAD

**Issue by compocas** [ruudk/PaymentMollieBundle#20]
Hello again,
Does this bundle accept other payment methods other than 
ideal, creditcard, mistercash and sofort???

Is it simple to integrate bank transfer and belfius ??

thank you in advance

**Comment by ruudk** [comment]
It should be possible I think. What if you just add those methods to the config?

**Comment by Fordiag** [comment]
How to write them?
- bank transfer ?
- banktransfer ?
didn't found in the doc...

**Comment by ruudk** [comment]
Exact same way as mollie writes them...

**Comment by ruudk** [comment]
Would be great if you could do a small PR to add this to the docs :)

**Comment by Fordiag** [comment]
I have a "can't create mollie payment" error when I choose "banktransfer" or "belfius"...

**Comment by ruudk** [comment]
Ah, I think you have to create a PR to add the methods here:

https://github.com/ruudk/PaymentMollieBundle/search?utf8=%E2%9C%93&q=creditcard

**Comment by PR3M1UM** [comment]
@ruudk I tried adding paysafecard and bancontact by adding those files, services and a reference in DefaultPlugin, but it keeps throwing a CommunicationException (Can't create Mollie payment). Can you reproduce this?

**Comment by ruudk** [comment]
You can try to debug the exception. It's probably an invalid response from the Mollie API. 

Can you post the stack trace?
