### ISSUE TITLE
Dynamic mollie api keys

### ISSUE THREAD

**Issue by tonyellow** [ruudk/PaymentMollieBundle#26]
It would be nice to have an option to provide dynamic API keys. At the moment we can only provide an API key through the config. 

If someone knows a solution for the time being, please share it!

**Comment by ruudk** [comment]
What about:
```php
$container->get('ruudk_payment_mollie.gateway')->setApiKey('my-key');
```
?

**Comment by tonyellow** [comment]
Wow, didn't realize it was that simple! I hope this topic can help others looking for this feature. Thanks for your message (AND THIS GREAT PLUGIN)!
