### ISSUE TITLE
Logging does get handled

### ISSUE THREAD

**Issue by Maff-** [ruudk/PaymentMollieBundle#34]
We're using RuudkPaymentMollieBundle in a Symfony 4.3 project. When debugging a payment issue I noticed although logging is enabled (`ruudk_payment_mollie.logger = true`), no messages got written to the log files.

After some further digging it turns out no _handlers_ are attached to the `monolog.logger.ruudk_payment_mollie` service;

```
Information for Service "monolog.logger.ruudk_payment_mollie"
=============================================================

 ---------------- ---------------------------------------------
  Option           Value
 ---------------- ---------------------------------------------
  Service ID       monolog.logger.ruudk_payment_mollie
  Class            Symfony\Bridge\Monolog\Logger
  Tags             -
  Calls            pushProcessor, pushProcessor, pushProcessor
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
 ---------------- ---------------------------------------------
```
above is missing calls to `pushHandler`.

I was able to get things working by explicitly defining the `ruudk_payment_mollie` channel via the monolog config;
```yaml
monolog:
    channels: [ruudk_payment_mollie]
```

I'm not sure if that 'solution' would be the way to go tough. Other suggestions are of course welcome.

**Comment by ruudk** [comment]
That's the way to go indeed. 

FYI: I no longer use JMSPaymentCoreBundle and therefore am not maintaining this anymore.
