### ISSUE TITLE
Question about the IdealFormType

### ISSUE THREAD

**Issue by verschoof** [ruudk/PaymentMollieBundle#4]
Hi Ruud,

I was searching for a PaymentMollieBundle for Symfony2. While I was scanning your code I saw this:

https://github.com/ruudk/PaymentMollieBundle/blob/master/Form/IdealType.php#L22

Is this line of code specific for your own situation?

**Comment by ruudk** [comment]
Well... What this does, is loading a cached file with all the issuers of Mollie. As more and more banks join iDEAL they can add banks over time.

While you warmup the cache of Symfony this file is created, see: https://github.com/ruudk/PaymentMollieBundle/blob/master/CacheWarmer/IssuersCacheWarmer.php
