### ISSUE TITLE
Missende service foutmelding

### ISSUE THREAD

**Issue by xoniq** [ruudk/PaymentMollieBundle#7]
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
The service "ruudk_payment_mollie.controller.notification" has a dependency on a non-existent service "payment.plugin_controller".

**Comment by rickerd** [comment]
You'll need to register the JMS core bundle in the appkernel + set the secret for the JMS core bundle.
This is not an error in the PaymentMollieBundle. Its lack of knowledge i think.

**Comment by ruudk** [comment]
Indeed :)

**Comment by phpdeveloper1** [comment]
http://jmspaymentcorebundle.readthedocs.io/en/stable/setup.html
