### ISSUE TITLE
Locked on Symfony2

### ISSUE THREAD

**Issue by rickerd** [ruudk/PaymentMollieBundle#8]
Why is the bundle locked on Symfony2? Is it not compatible with version 3?

**Comment by ruudk** [comment]
There is no real reason for it. Our own application runs on 2.8. Feel free to submit a PR to allow SF 3.0 :)

**Comment by rickerd** [comment]
Nice, i will do that. 

---

Met vriendelijke groet,
Rick de Graaff

Verstuurd vanaf mijn iPhone 6

**Comment by rickerd** [comment]
I've added a PR.
Also added a PR to the JMS PaymentCoreBundle. This is also locked on version 2
